### PR TITLE
Added NegativeFilter

### PR DESCRIPTION
**Pull request by AaronHand**
Added NegativeFilter & LaplacianFilter.   Laplacian doesn't seem to be working correctly with computeWeightedAverages, can someone take a look?

### CODE REVIEW

**Comment by suleecao** [comment]
I will be on a flight to Chicago when this is due. Will finish it before then but can someone else submit it? Also, is Serge still in the group? Thanks.

**Comment by AaronHand** [comment]
If you are taking off, you should add one of us to contrib list so we can merge pull requests

**Comment by suleecao** [comment]
I just did.

**Comment by suleecao** [comment]
The LaplacianFilter shouldn't be normalized.

**Pull request merged**
